version: 2
jobs:
  build:
    working_directory: ~/item_cart
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: item_cart_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-{{ checksum "yarn.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Yarn install dependencies
      - run:
          name: Install javascript dependencies
          command: ./bin/yarn check || ./bin/yarn install

      - run: sudo apt install postgresql-client

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Store node_modules cache
      - save_cache:
          key: rails-demo-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bin/rails test
      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

      # collect reports
      - store_test_results:
          path: tmp/test-results
      - store_artifacts:
          path: tmp/test-results
          destination: test-results

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

      # deploy to heroku
      - run: bash .circleci/setup-heroku.sh
#        - add_ssh_keys:
#          fingerprints:
#            - "d1:a7:c8:95:54:06:be:55:8a:c1:55:59:28:d5:be:3a"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku restart
            fi